name: Enable auto-merge for maintainer PRs

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-automerge:
    # Only act on PRs authored by the repository maintainer and not drafts
    if: github.event.pull_request.user.login == 'nwhistler' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

