name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff trufflehog

      - name: Python syntax check
        run: python -m compileall -q .

      - name: Python lint (ruff)
        run: |
          ruff version
          ruff check .

      - name: TruffleHog (git history)
        run: trufflehog git file://"$GITHUB_WORKSPACE" --fail --only-verified

      - name: TruffleHog (filesystem)
        run: trufflehog filesystem . --fail --only-verified
