name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff trufflehog

      - name: Python syntax check
        run: python -m compileall -q .

      - name: Python lint (ruff)
        run: |
          ruff version
          ruff check .

      - name: TruffleHog (filesystem)
        uses: trufflesecurity/trufflehog@v3.71.0
        with:
          path: .
          extra_args: --only-verified --fail

      - name: TruffleHog (PR diff)
        if: github.event_name == 'pull_request'
        uses: trufflesecurity/trufflehog@v3.71.0
        with:
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.sha }}
          extra_args: --only-verified --fail
